// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bcmeccipher.proto

package com.bcm.messenger.common.crypto;

public final class ECCipherProto {
  private ECCipherProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ECCipherDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bcm.ECCipherData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>bytes ciphertext = 2;</code>
     */
    com.google.protobuf.ByteString getCiphertext();

    /**
     * <code>bytes cipherkey = 3;</code>
     */
    com.google.protobuf.ByteString getCipherkey();

    /**
     * <code>bytes mac = 4;</code>
     */
    com.google.protobuf.ByteString getMac();
  }
  /**
   * Protobuf type {@code bcm.ECCipherData}
   */
  public  static final class ECCipherData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bcm.ECCipherData)
      ECCipherDataOrBuilder {
    // Use ECCipherData.newBuilder() to construct.
    private ECCipherData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ECCipherData() {
      version_ = 0;
      ciphertext_ = com.google.protobuf.ByteString.EMPTY;
      cipherkey_ = com.google.protobuf.ByteString.EMPTY;
      mac_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ECCipherData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              version_ = input.readInt32();
              break;
            }
            case 18: {

              ciphertext_ = input.readBytes();
              break;
            }
            case 26: {

              cipherkey_ = input.readBytes();
              break;
            }
            case 34: {

              mac_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ECCipherProto.internal_static_bcm_ECCipherData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ECCipherProto.internal_static_bcm_ECCipherData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ECCipherData.class, Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int CIPHERTEXT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString ciphertext_;
    /**
     * <code>bytes ciphertext = 2;</code>
     */
    public com.google.protobuf.ByteString getCiphertext() {
      return ciphertext_;
    }

    public static final int CIPHERKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString cipherkey_;
    /**
     * <code>bytes cipherkey = 3;</code>
     */
    public com.google.protobuf.ByteString getCipherkey() {
      return cipherkey_;
    }

    public static final int MAC_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString mac_;
    /**
     * <code>bytes mac = 4;</code>
     */
    public com.google.protobuf.ByteString getMac() {
      return mac_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeInt32(1, version_);
      }
      if (!ciphertext_.isEmpty()) {
        output.writeBytes(2, ciphertext_);
      }
      if (!cipherkey_.isEmpty()) {
        output.writeBytes(3, cipherkey_);
      }
      if (!mac_.isEmpty()) {
        output.writeBytes(4, mac_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (!ciphertext_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, ciphertext_);
      }
      if (!cipherkey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, cipherkey_);
      }
      if (!mac_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, mac_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ECCipherData)) {
        return super.equals(obj);
      }
      ECCipherData other = (ECCipherData) obj;

      boolean result = true;
      result = result && (getVersion()
          == other.getVersion());
      result = result && getCiphertext()
          .equals(other.getCiphertext());
      result = result && getCipherkey()
          .equals(other.getCipherkey());
      result = result && getMac()
          .equals(other.getMac());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + CIPHERTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getCiphertext().hashCode();
      hash = (37 * hash) + CIPHERKEY_FIELD_NUMBER;
      hash = (53 * hash) + getCipherkey().hashCode();
      hash = (37 * hash) + MAC_FIELD_NUMBER;
      hash = (53 * hash) + getMac().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ECCipherData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ECCipherData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ECCipherData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ECCipherData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ECCipherData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ECCipherData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ECCipherData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ECCipherData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ECCipherData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ECCipherData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ECCipherData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bcm.ECCipherData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bcm.ECCipherData)
        ECCipherDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ECCipherProto.internal_static_bcm_ECCipherData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ECCipherProto.internal_static_bcm_ECCipherData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ECCipherData.class, Builder.class);
      }

      // Construct using com.bcm.messenger.common.crypto.ECCipherProto.ECCipherData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        version_ = 0;

        ciphertext_ = com.google.protobuf.ByteString.EMPTY;

        cipherkey_ = com.google.protobuf.ByteString.EMPTY;

        mac_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ECCipherProto.internal_static_bcm_ECCipherData_descriptor;
      }

      public ECCipherData getDefaultInstanceForType() {
        return ECCipherData.getDefaultInstance();
      }

      public ECCipherData build() {
        ECCipherData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ECCipherData buildPartial() {
        ECCipherData result = new ECCipherData(this);
        result.version_ = version_;
        result.ciphertext_ = ciphertext_;
        result.cipherkey_ = cipherkey_;
        result.mac_ = mac_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ECCipherData) {
          return mergeFrom((ECCipherData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ECCipherData other) {
        if (other == ECCipherData.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getCiphertext() != com.google.protobuf.ByteString.EMPTY) {
          setCiphertext(other.getCiphertext());
        }
        if (other.getCipherkey() != com.google.protobuf.ByteString.EMPTY) {
          setCipherkey(other.getCipherkey());
        }
        if (other.getMac() != com.google.protobuf.ByteString.EMPTY) {
          setMac(other.getMac());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ECCipherData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ECCipherData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString ciphertext_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes ciphertext = 2;</code>
       */
      public com.google.protobuf.ByteString getCiphertext() {
        return ciphertext_;
      }
      /**
       * <code>bytes ciphertext = 2;</code>
       */
      public Builder setCiphertext(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ciphertext_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes ciphertext = 2;</code>
       */
      public Builder clearCiphertext() {
        
        ciphertext_ = getDefaultInstance().getCiphertext();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString cipherkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes cipherkey = 3;</code>
       */
      public com.google.protobuf.ByteString getCipherkey() {
        return cipherkey_;
      }
      /**
       * <code>bytes cipherkey = 3;</code>
       */
      public Builder setCipherkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cipherkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes cipherkey = 3;</code>
       */
      public Builder clearCipherkey() {
        
        cipherkey_ = getDefaultInstance().getCipherkey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString mac_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes mac = 4;</code>
       */
      public com.google.protobuf.ByteString getMac() {
        return mac_;
      }
      /**
       * <code>bytes mac = 4;</code>
       */
      public Builder setMac(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes mac = 4;</code>
       */
      public Builder clearMac() {
        
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bcm.ECCipherData)
    }

    // @@protoc_insertion_point(class_scope:bcm.ECCipherData)
    private static final ECCipherData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ECCipherData();
    }

    public static ECCipherData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ECCipherData>
        PARSER = new com.google.protobuf.AbstractParser<ECCipherData>() {
      public ECCipherData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ECCipherData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ECCipherData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ECCipherData> getParserForType() {
      return PARSER;
    }

    public ECCipherData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bcm_ECCipherData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bcm_ECCipherData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021bcmeccipher.proto\022\003bcm\"S\n\014ECCipherData" +
      "\022\017\n\007version\030\001 \001(\005\022\022\n\nciphertext\030\002 \001(\014\022\021\n" +
      "\tcipherkey\030\003 \001(\014\022\013\n\003mac\030\004 \001(\014B0\n\037com.bcm" +
      ".messenger.common.cryptoB\rECCipherProtob" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bcm_ECCipherData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bcm_ECCipherData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bcm_ECCipherData_descriptor,
        new String[] { "Version", "Ciphertext", "Cipherkey", "Mac", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
