/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class p */

#ifndef _Included_P
#define _Included_P
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_bcm_messenger_common_p_a
        (JNIEnv *env, jclass jclazz, jobject contextObject);

JNIEXPORT jstring JNICALL Java_com_bcm_messenger_common_p_b
         (JNIEnv *env, jclass jclazz, jobject contextObject);

#ifdef __cplusplus
}
#endif
#endif //IM_ANDROID_P_H
