package com.bcm.route.processor;

public class Consts {
    public static final String PACKAGE_NAME = "com.bcm.route.path";
    public static final String PACKAGE_ANNOS = "com.bcm.route.annotation";
    public static final String PACKAGE_API = "com.bcm.route.api";

    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_ANDROIDX = "androidx.fragment.app.Fragment";
    public static final String PROVIDER = "com.bcm.route.api.IRouteProvider";
    public static final String SERVICE = "android.app.Service";

    public static final String CONST_ANNOTATION = "com.bcm.route.annotation.Route";

    public static final String MODULE_NAME = "MODULE_NAME";

    public static final String I_ROUTE_PATHS = "IRoutePaths";

    public static final String AUTO_GEN_DOCS = "THIS FILE IS AUTO GENERATED BY BCM, DO NOT EDIT IT!\n";
}
